### ISSUE TITLE
Parameterize CLA check URLs

### ISSUE THREAD

**Issue by abose** [aicore/template-nodejs#48]
Currently, the URL to obtain personal/employer CLA file is hard coded [See Link here](https://github.com/aicore/template-nodejs/blob/main/.github/workflows/python/verify_cla_signature_pr.py#L81) . We sould parameterize it as a github environment variable.

See docs on how to pass environment variables from action yml files: https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by psdhanesh7** [comment]
> Currently, the URL to obtain personal/employer CLA file is hard coded [See Link here](https://github.com/aicore/template-nodejs/blob/main/.github/workflows/python/verify_cla_signature_pr.py#L81) . We sould parameterize it as a github environment variable.
> 
> See docs on how to pass environment variables from action yml files: https://docs.github.com/en/actions/learn-github-actions/environment-variables

Issue solved in pull request https://github.com/aicore/template-nodejs/pull/49#issue-1215550697.

**Comment by abose** [comment]
LGTM . Thanks for contributing @psdhanesh7 
Closing.
